name: Test
on:
  pull_request:
  push: { branches: main }

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --all-features

  test:
    name: Run test suite
    runs-on: ubuntu-latest
    container: rust:latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create test config
      run: |
        cp example.config.toml config.toml
        sed -i 's/localhost/postgres/g' config.toml
      shell: bash
    
    - name: Run tests
      run: cargo test
  
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: rustup component add rustfmt --toolchain nightly
      - run: cargo fmt --all -- --check
  
  clippy:
    name: Check for linting errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add clippy
      - run: cargo clippy --all-features -- -D warnings